<a href="https://colab.research.google.com/github/pmatkowska94/MSC_Data_Science/blob/main/CHO_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test_df.csv to test_df.csv
Saving train_df.csv to train_df.csv
Saving val_df.csv to val_df.csv

In [ ]:
train_df = pd.read_csv('train_df.csv')
test_df = pd.read_csv('test_df.csv')
val_df = pd.read_csv('val_df.csv')

**Missing Values**

kla > 50 % will be dropped from dataset

np and impeller_no are variables used for engineering features but irrelevant in the dataset, will be dropped

critical information missing: time, vcd, volume will be dropped

vvm is important and will be imputed

In [ ]:
train_df.drop(columns=['kla', 'impeller_d', 'np', 'do', 'impeller_no', 'agitation'], inplace=True)
test_df.drop(columns=['kla', 'impeller_d', 'np', 'do', 'impeller_no', 'agitation'], inplace=True)
val_df.drop(columns=['kla', 'impeller_d', 'np', 'do', 'impeller_no', 'agitation'], inplace=True)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1291 entries, 0 to 1290
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        1272 non-null   object
 1   p_id          1291 non-null   int64
 2   r_id          1291 non-null   int64
 3   clone_id      1291 non-null   int64
 4   time          1264 non-null   float64
 5   vcd           1169 non-null   float64
 6   volume        1169 non-null   float64
 7   p_v           1229 non-null   float64
 8   vvm           765 non-null    float64
 9   tip_speed     1155 non-null   float64
 10  reynolds      1155 non-null   float64
 11  aspect_r      1088 non-null   float64
 12  group_volume  1291 non-null   float64
 13  seed_d        1210 non-null   float64
 14  cell_type     1291 non-null   object
dtypes: float64(10), int64(3), object(2)
memory usage: 151.4+ KB

In [ ]:
train_df = train_df.dropna(subset=['vcd', 'time'])
test_df = test_df.dropna(subset=['vcd', 'time'])
val_df = val_df.dropna(subset=['vcd', 'time'])

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1168 entries, 0 to 1290
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        1168 non-null   object
 1   p_id          1168 non-null   int64
 2   r_id          1168 non-null   int64
 3   clone_id      1168 non-null   int64
 4   time          1168 non-null   float64
 5   vcd           1168 non-null   float64
 6   volume        1166 non-null   float64
 7   p_v           1166 non-null   float64
 8   vvm           762 non-null    float64
 9   tip_speed     1152 non-null   float64
 10  reynolds      1152 non-null   float64
 11  aspect_r      1086 non-null   float64
 12  group_volume  1168 non-null   float64
 13  seed_d        1168 non-null   float64
 14  cell_type     1168 non-null   object
dtypes: float64(10), int64(3), object(2)
memory usage: 146.0+ KB

In [ ]:
train_df = train_df.dropna(subset=['volume'])
test_df = test_df.dropna(subset=['volume'])
val_df = val_df.dropna(subset=['volume'])

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1166 entries, 0 to 1290
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        1166 non-null   object
 1   p_id          1166 non-null   int64
 2   r_id          1166 non-null   int64
 3   clone_id      1166 non-null   int64
 4   time          1166 non-null   float64
 5   vcd           1166 non-null   float64
 6   volume        1166 non-null   float64
 7   p_v           1166 non-null   float64
 8   vvm           762 non-null    float64
 9   tip_speed     1152 non-null   float64
 10  reynolds      1152 non-null   float64
 11  aspect_r      1086 non-null   float64
 12  group_volume  1166 non-null   float64
 13  seed_d        1166 non-null   float64
 14  cell_type     1166 non-null   object
dtypes: float64(10), int64(3), object(2)
memory usage: 145.8+ KB

In [ ]:
print(train_df[train_df['tip_speed'].isna() | train_df['reynolds'].isna()])

     vessel  p_id  r_id  clone_id  time    vcd  volume    p_v  vvm  tip_speed  \
0   ambr 15     1     1         1   0.0   0.41    15.0  220.8  0.0        NaN
1   ambr 15     1     1         1   1.0   2.67    15.0  220.8  0.0        NaN
2   ambr 15     1     1         1   2.0   4.88    15.0  220.8  0.0        NaN
3   ambr 15     1     1         1   3.0   7.09    15.0  220.8  0.0        NaN
4   ambr 15     1     1         1   4.0  11.16    15.0  220.8  0.0        NaN
5   ambr 15     1     1         1   5.0  15.09    15.0  220.8  0.0        NaN
6   ambr 15     1     1         1   6.0  17.26    15.0  220.8  0.0        NaN
7   ambr 15     1     1         1   7.0  20.02    15.0  220.8  0.0        NaN
8   ambr 15     1     1         1   8.0  19.20    15.0  220.8  0.0        NaN
9   ambr 15     1     1         1   9.0  18.30    15.0  220.8  0.0        NaN
10  ambr 15     1     1         1  10.0  16.22    15.0  220.8  0.0        NaN
11  ambr 15     1     1         1  11.0  15.23    15.0  220.8  0.0        NaN
12  ambr 15     1     1         1  12.0  15.14    15.0  220.8  0.0        NaN
13  ambr 15     1     1         1  13.0  12.97    15.0  220.8  0.0        NaN

    reynolds  aspect_r  group_volume  seed_d cell_type
0        NaN       NaN         0.015    0.41       cho
1        NaN       NaN         0.015    0.41       cho
2        NaN       NaN         0.015    0.41       cho
3        NaN       NaN         0.015    0.41       cho
4        NaN       NaN         0.015    0.41       cho
5        NaN       NaN         0.015    0.41       cho
6        NaN       NaN         0.015    0.41       cho
7        NaN       NaN         0.015    0.41       cho
8        NaN       NaN         0.015    0.41       cho
9        NaN       NaN         0.015    0.41       cho
10       NaN       NaN         0.015    0.41       cho
11       NaN       NaN         0.015    0.41       cho
12       NaN       NaN         0.015    0.41       cho
13       NaN       NaN         0.015    0.41       cho

In [ ]:
train_df = train_df.dropna(subset=['tip_speed'])

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1152 entries, 15 to 1290
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        1152 non-null   object
 1   p_id          1152 non-null   int64
 2   r_id          1152 non-null   int64
 3   clone_id      1152 non-null   int64
 4   time          1152 non-null   float64
 5   vcd           1152 non-null   float64
 6   volume        1152 non-null   float64
 7   p_v           1152 non-null   float64
 8   vvm           748 non-null    float64
 9   tip_speed     1152 non-null   float64
 10  reynolds      1152 non-null   float64
 11  aspect_r      1086 non-null   float64
 12  group_volume  1152 non-null   float64
 13  seed_d        1152 non-null   float64
 14  cell_type     1152 non-null   object
dtypes: float64(10), int64(3), object(2)
memory usage: 144.0+ KB

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 242 entries, 0 to 272
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        242 non-null    object
 1   p_id          242 non-null    int64
 2   r_id          242 non-null    int64
 3   clone_id      242 non-null    int64
 4   time          242 non-null    float64
 5   vcd           242 non-null    float64
 6   volume        242 non-null    float64
 7   p_v           242 non-null    float64
 8   vvm           184 non-null    float64
 9   tip_speed     242 non-null    float64
 10  reynolds      242 non-null    float64
 11  aspect_r      212 non-null    float64
 12  group_volume  242 non-null    float64
 13  seed_d        242 non-null    float64
 14  cell_type     242 non-null    object
dtypes: float64(10), int64(3), object(2)
memory usage: 30.2+ KB

In [ ]:
val_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 0 to 180
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vessel        175 non-null    object
 1   p_id          175 non-null    int64
 2   r_id          175 non-null    int64
 3   clone_id      175 non-null    int64
 4   time          175 non-null    float64
 5   vcd           175 non-null    float64
 6   volume        175 non-null    float64
 7   p_v           175 non-null    float64
 8   vvm           84 non-null     float64
 9   tip_speed     175 non-null    float64
 10  reynolds      175 non-null    float64
 11  aspect_r      162 non-null    float64
 12  group_volume  175 non-null    float64
 13  seed_d        175 non-null    float64
 14  cell_type     175 non-null    object
dtypes: float64(10), int64(3), object(2)
memory usage: 21.9+ KB

All critical missing values were excluded, including time, VCD, and volume. Redundant variables such as impeller number, impeller power number, agitation, and impeller diameter were also removed. kLa was excluded due to over 50% missing data. DO was treated as a setpoint rather than a process variable.

In [ ]:
train_df = train_df.drop(columns=['vessel'])
test_df = test_df.drop(columns=['vessel'])
val_df = val_df.drop(columns=['vessel'])

**Missing VVM**

In [ ]:
train_df.groupby('p_id')['vvm'].mean()

p_id
1     0.044167
2          NaN
3     0.031869
4     0.004060
5     0.010000
6     3.552610
7     0.003734
8     0.002500
9     0.003100
11    0.000000
12         NaN
13    0.009633
14         NaN
15    0.020000
16    0.020000
17    0.098222
18    0.010000
20    0.010000
21    0.025000
22    0.035000
23         NaN
24         NaN
25         NaN
26         NaN
Name: vvm, dtype: float64

In [ ]:
train_df.groupby('p_id')['vvm'].median()

p_id
1     0.035000
2          NaN
3     0.040000
4     0.000000
5     0.010000
6     0.025113
7     0.002500
8     0.002500
9     0.003100
11    0.000000
12         NaN
13    0.010000
14         NaN
15    0.020000
16    0.020000
17    0.100000
18    0.010000
20    0.010000
21    0.025000
22    0.035000
23         NaN
24         NaN
25         NaN
26         NaN
Name: vvm, dtype: float64

In [ ]:
train_df.groupby('group_volume')['vvm'].median()

group_volume
0.015          NaN
0.250       0.0400
1.000          NaN
1.300       0.0025
2.000       0.0100
3.000       0.0000
5.000       0.0100
10.000      0.0100
15.000      0.0100
50.000      0.0350
100.000     0.0100
200.000     0.0200
250.000        NaN
500.000     0.0100
2000.000       NaN
Name: vvm, dtype: float64

In [ ]:
train_df['vvm'] = train_df.groupby('p_id')['vvm'].transform(lambda x: x.fillna(x.median()))
train_df['vvm'] = train_df.groupby('group_volume')['vvm'].transform(lambda x: x.fillna(x.median()))
train_df['vvm'] = train_df['vvm'].fillna(0.02)

In [ ]:
train_df.groupby('group_volume')['vvm'].median()

group_volume
0.015       0.0200
0.250       0.0400
1.000       0.0200
1.300       0.0025
2.000       0.0100
3.000       0.0000
5.000       0.0100
10.000      0.0100
15.000      0.0100
50.000      0.0350
100.000     0.0100
200.000     0.0200
250.000     0.0200
500.000     0.0100
2000.000    0.0200
Name: vvm, dtype: float64

Missing vvm values were imputed using a biologically informed approach. They were first filled with the median per process (p_id), then with the median per reactor scale (group_volume), and finally replaced with a typical CHO value of 0.02 VVM.

In [ ]:
test_df['vvm'] = test_df.groupby('p_id')['vvm'].transform(lambda x: x.fillna(x.median()))
test_df['vvm'] = test_df.groupby('group_volume')['vvm'].transform(lambda x: x.fillna(x.median()))
test_df['vvm'] = test_df['vvm'].fillna(0.02)

In [ ]:
val_df['vvm'] = val_df.groupby('p_id')['vvm'].transform(lambda x: x.fillna(x.median()))
val_df['vvm'] = val_df.groupby('group_volume')['vvm'].transform(lambda x: x.fillna(x.median()))
val_df['vvm'] = val_df['vvm'].fillna(0.02)

In [ ]:
test_df.groupby('group_volume')['vvm'].median()

group_volume
3.0       0.010000
14.0      0.015000
50.0      0.020000
250.0     0.015000
2000.0    0.008000
5000.0    0.016639
Name: vvm, dtype: float64

In [ ]:
val_df.groupby('group_volume')['vvm'].median()

group_volume
5.0       0.02000
50.0      0.02000
250.0     0.01500
500.0     0.02000
1000.0    0.01675
2000.0    0.01000
Name: vvm, dtype: float64

In [ ]:
train_df.isnull().sum()

p_id             0
r_id             0
clone_id         0
time             0
vcd              0
volume           0
p_v              0
vvm              0
tip_speed        0
reynolds         0
aspect_r        66
group_volume     0
seed_d           0
cell_type        0
dtype: int64

**Missing aspect ratio**

In [ ]:
train_df.groupby('p_id')['aspect_r'].median()

p_id
1     1.500
2     1.800
3     2.000
4     2.000
5     2.080
6     2.700
7     2.000
8     2.000
9     2.000
11    2.050
12    1.500
13    2.100
14    2.100
15    1.000
16    1.000
17    1.800
18    2.250
20    2.100
21    2.700
22    2.700
23    2.000
24    1.500
25    1.925
26    2.250
Name: aspect_r, dtype: float64

In [ ]:
train_df.groupby('group_volume')['aspect_r'].median()

group_volume
0.015        NaN
0.250       2.00
1.000       2.10
1.300       2.00
2.000       2.08
3.000       2.00
5.000       2.20
10.000      2.00
15.000      2.10
50.000      2.90
100.000     2.50
200.000     1.50
250.000     1.50
500.000     2.50
2000.000    1.50
Name: aspect_r, dtype: float64

In [ ]:
train_df['aspect_r'] = train_df.groupby('p_id')['aspect_r'].transform(lambda x: x.fillna(x.median()))
train_df['aspect_r'] = train_df.groupby('group_volume')['aspect_r'].transform(lambda x: x.fillna(x.median()))
train_df['aspect_r'] = train_df['aspect_r'].fillna(2.0)

In [ ]:
test_df['aspect_r'] = test_df.groupby('p_id')['aspect_r'].transform(lambda x: x.fillna(x.median()))
test_df['aspect_r'] = test_df.groupby('group_volume')['aspect_r'].transform(lambda x: x.fillna(x.median()))
test_df['aspect_r'] = test_df['aspect_r'].fillna(2.0)

In [ ]:
val_df['aspect_r'] = val_df.groupby('p_id')['aspect_r'].transform(lambda x: x.fillna(x.median()))
val_df['aspect_r'] = val_df.groupby('group_volume')['aspect_r'].transform(lambda x: x.fillna(x.median()))
val_df['aspect_r'] = val_df['aspect_r'].fillna(2.0)

Missing aspect_r values were imputed using same as vvm approach. They were first filled with the median per process (p_id), then with the median per reactor scale (group_volume), and finally replaced with a default value of 2.0, typical for stirred-tank bioreactors.

In [ ]:
train_df.isnull().sum()

p_id            0
r_id            0
clone_id        0
time            0
vcd             0
volume          0
p_v             0
vvm             0
tip_speed       0
reynolds        0
aspect_r        0
group_volume    0
seed_d          0
cell_type       0
dtype: int64

In [ ]:
test_df.isnull().sum()

p_id            0
r_id            0
clone_id        0
time            0
vcd             0
volume          0
p_v             0
vvm             0
tip_speed       0
reynolds        0
aspect_r        0
group_volume    0
seed_d          0
cell_type       0
dtype: int64

In [ ]:
val_df.isnull().sum()

p_id            0
r_id            0
clone_id        0
time            0
vcd             0
volume          0
p_v             0
vvm             0
tip_speed       0
reynolds        0
aspect_r        0
group_volume    0
seed_d          0
cell_type       0
dtype: int64

In [ ]:
print(len(train_df), len(val_df), len(test_df))

1152 175 242

In [ ]:
train_df.to_csv('train_df.csv', index=False)
val_df.to_csv('val_df.csv', index=False)
test_df.to_csv('test_df.csv', index=False)

In [ ]:
files.download('train_df.csv')
files.download('val_df.csv')
files.download('test_df.csv')